[project]
name = "shifts_pro"
version = "1.2.0"
description = "Календарь смен PRO"
requires-python = ">=3.12,<3.13"
dependencies = [
    "flet==0.86.5",
    "flet-charts==0.86.5",
    "fpdf2==2.8.2",
]

[tool.flet]
org = "com.penalty7master"
product = "Календарь смен PRO"
company = "penalty7master"

[tool.flet.app]
module = "main"

[tool.flet.android]
target_arch = ["arm64-v8a"]
